-- MySQL Script generated by MySQL Workbench
-- Mon Dec 14 16:06:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SDS_group4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SDS_group4` ;

-- -----------------------------------------------------
-- Schema SDS_group4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SDS_group4` DEFAULT CHARACTER SET utf8 ;
#SHOW WARNINGS;
USE `SDS_group4` ;

-- -----------------------------------------------------
-- Table `BigFile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BigFile` ;

#SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `BigFile` (`bigFileID` INT NOT NULL AUTO_INCREMENT,`DataPath` VARCHAR(255) NULL,`UpdatedCount` INT NULL,`Hot` TINYINT NULL,`UserID` INT NULL,`FileID` INT NULL,PRIMARY KEY (`bigFileID`))
#ENGINE = InnoDB;

#SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Metadata` ;

#SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Metadata` (`FileID` INT NOT NULL AUTO_INCREMENT,`UserID` INT NULL DEFAULT NULL,`FileName` VARCHAR(255) NULL,`FileSize` INT NULL,`ModifyTime` DATETIME NULL,PRIMARY KEY (`FileID`))
#ENGINE = InnoDB;

#SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SmallFile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmallFile` ;

#SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SmallFile` (`smallFileID` INT NOT NULL AUTO_INCREMENT,`Data` MEDIUMBLOB NULL,`UpdatedCount` INT NULL,`Hot` TINYINT NULL,`UserID` INT NULL,`FileID` INT NULL,PRIMARY KEY (`smallFileID`))
#ENGINE = InnoDB;

#SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

#SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (`UserID` INT NOT NULL,`UserName` CHAR(20) NULL,PRIMARY KEY (`UserID`))
#ENGINE = InnoDB;
INSERT INTO `SDS_group4`.`User` (`UserID`, `UserName`) VALUES ('1', 'ChulWoo');
INSERT INTO `SDS_group4`.`User` (`UserID`, `UserName`) VALUES ('2', 'SeonJeong');
INSERT INTO `SDS_group4`.`User` (`UserID`, `UserName`) VALUES ('3', 'SeongJin');
INSERT INTO `SDS_group4`.`User` (`UserID`, `UserName`) VALUES ('4', 'YongMoon');

#SHOW WARNINGS;
ALTER TABLE User MODIFY UserID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE Metadata MODIFY FileID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE BigFile MODIFY bigFileID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE SmallFile MODIFY smallFileID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE Metadata MODIFY ModifyTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
